[mouse]
hide_when_typing = true

[cursor.style]
shape = "Block"

[font]
size = 12.0
normal = { family = "MesloLGLDZ Nerd Font", style = "Regular" }
bold   = { family = "MesloLGLDZ Nerd Font", style = "Bold"    }
italic = { family = "MesloLGLDZ Nerd Font", style = "Italic"  }

[window]
opacity = 0
dynamic_padding = true

